### ISSUE TITLE
Venue API is returning arrays for many genres and single variables for one

### ISSUE THREAD

**Issue by ttocskcaj** [OpenPolytechnicBITProjectGroup/Musician-Venue_App#27]
E.G.
Single genre:
```
{
name: "A Pub",
capacity: 9000,
location: "Timaru",
genres: "Classical"
}
```

Multi genre:
```
{
name: "The Grand",
capacity: "500",
location: "Wellington",
genres: [
  "Pop",
  "DJ/Electronic"
]
}
```

This means that angular can't ng-repeat the genres if there's only one.

The API needs to return an array of genres, even if there's only one linked to a venue.

**Comment by lxdnz254** [comment]
It should be returning an array of genres... That's what the test is for. 1
genre  is a genre array of length 1

**Comment by ttocskcaj** [comment]
It's definitely just returning a variable with one genre:
![image](https://user-images.githubusercontent.com/453862/28857420-82ff9daa-779d-11e7-97d8-dc27329dc98a.png)

**Comment by ttocskcaj** [comment]
I'll have a play with it and see what's up

**Comment by lxdnz254** [comment]
It couks be the post method not storing as an array.
I'm putting milk in my containers so I'm out for another hour or so

**Comment by ttocskcaj** [comment]
Hope you're using openpolytechnic's new system to help you with that.. 😆

**Comment by ttocskcaj** [comment]
The issue seems to lie with the Neo4j restful API. It returns a single variable if there's one relation or an array if there are many relations.
![image](https://user-images.githubusercontent.com/453862/28857969-4dac095a-77a1-11e7-82a6-cbedab80ea52.png)

**Comment by lxdnz254** [comment]
I think the solution is to ensure genres is sent and received as an array. In venue.js on client and server side, set this.genres to this.genres[]

**Comment by ttocskcaj** [comment]
Can't do that as JS doesn't support types. Unless I'm misinterpreting what you're saying. I'll get db_api.js to convert any single variables to an array as a tempory fix.

**Comment by lxdnz254** [comment]
Yep I'm still holding the container waiting for my data to be sent to cowNZ
so I can be paid my $50, so can't access screen yet

On 2/08/2017 5:18 PM, "Jack Scott" <notifications@github.com> wrote:

Can't do that as JS doesn't support types. Unless I'm misinterpreting what
you're saying. I'll get db_api.js to convert any single variables to an
array as a tempory fix.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/OpenPolytechnicBITProjectGroup/Musician-Venue_App/issues/27#issuecomment-319570078>,
or mute the thread

**Comment by lxdnz254** [comment]
Check the api on 'lodash' I'm sure it can turn a variable to an array e.g. `_.genres.toArray()` or something like that

**Comment by ttocskcaj** [comment]
Got a fix, and sorted minified css and js for you. Check out PR #28  when you get time
